[build-system]
requires = ["setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "spherex"
version = "0.0.1"
requires-python = ">=3.10,<3.14"
dependencies = [
    "astropy>=7.1.0",
    "numpy>=2.3.0",
    "pandas",
    "matplotlib",
    "photutils>=2.2.0",
    "tqdm",
    "pydantic",
    "sqlalchemy>=2.0.42",
    "psycopg>=3.2.9",
    "geoalchemy2",
    "pyarrow>=21.0.0",
    "fastparquet>=2024.11.0",
]
