from sqlalchemy import Column, Integer, Float, String, Boolean, Sequence, VARCHAR
from geoalchemy2 import Geometry
from spherex.tables.base import SPHEREXBase


LATEST_QR_VERSION = 2
class ImagesTable(SPHEREXBase):
    """
    Full image table preserving the exact order of WCS header keywords.
    """

    __tablename__ = "images"
    __table_args__ = {"extend_existing": True}

    # --- Primary key ---
    uimageid = Column(
        Integer,
        Sequence(start=1, name="images_uimageid_seq"),
        autoincrement=True,
        primary_key=True,
    )

    # --- Header fields in exact order ---
    naxis = Column(Integer)
    naxis1 = Column(Integer)
    naxis2 = Column(Integer)
    pcount = Column(Integer)
    gcount = Column(Integer)

    detector = Column(Integer)
    obsid = Column(String(64))
    expidn = Column(String(64))
    date = Column(String(32))
    tsamp = Column(Float)
    kovr_a = Column(Integer)
    kovr_r = Column(Integer)
    kovr_p = Column(Integer)
    ovrdly = Column(Integer)
    surlim = Column(Integer)
    surdly = Column(Integer)
    trandly = Column(Integer)
    tcut = Column(Integer)
    ken_a = Column(Integer)
    ken_r = Column(Integer)
    ken_p = Column(Integer)
    ksn_a = Column(Integer)
    ksn_r = Column(Integer)
    ksn_p = Column(Integer)
    nskip = Column(Integer)
    nvisitrow = Column(Integer)
    nvisitcol = Column(Integer)
    mphan = Column(Integer)
    nchannel = Column(Integer)
    wchannel = Column(Integer)
    jref = Column(Integer)
    kref = Column(Integer)
    jactive = Column(Integer)
    kactive = Column(Integer)
    sps_target = Column(Integer)
    sps_flags = Column(String(64))
    obs_in_sband = Column(String(8))
    non_survey = Column(String(8))
    sgt_lat_midpt = Column(Float)
    sgt_lon_midpt = Column(Float)
    sgt_min_gcd2saa = Column(Float)
    sps_elon = Column(Float)
    sps_elat = Column(Float)
    sps_epa = Column(Float)
    l1dqaflg = Column(String(16))
    radesys = Column(String(16))
    l2_n_nonlinear = Column(Integer)
    psthresh = Column(Float)
    l2_n_persist = Column(Integer)
    detcoord = Column(String(16))
    l2_n_hot = Column(Integer)
    l2_n_cold = Column(Integer)
    omega_median = Column(Float)
    omega_stddev = Column(Float)
    finast = Column(Integer)
    wcsaxes = Column(Integer)
    crpix1 = Column(Float)
    crpix2 = Column(Float)
    pc1_1 = Column(Float)
    pc1_2 = Column(Float)
    pc2_1 = Column(Float)
    pc2_2 = Column(Float)
    cdelt1 = Column(Float)
    cdelt2 = Column(Float)
    cunit1 = Column(String(16))
    cunit2 = Column(String(16))
    ctype1 = Column(String(32))
    ctype2 = Column(String(32))
    crval1 = Column(Float)
    crval2 = Column(Float)
    lonpole = Column(Float)
    latpole = Column(Float)
    pxsrcmsk = Column(Float)
    l2_n_source = Column(Integer)
    l2_n_outlier = Column(Integer)
    psf_fwhm = Column(Float)
    l2dqaflg = Column(String(16))
    l2_n_transient = Column(Integer)
    l2_n_overflow = Column(Integer)
    l2_n_sur_error = Column(Integer)
    l2_n_nonfunc = Column(Integer)
    l2_n_dichroic = Column(Integer)
    l2_n_missing = Column(Integer)
    l2_n_fullsample = Column(Integer)
    l2_n_phanmiss = Column(Integer)
    a_order = Column(Integer)
    a_0_0 = Column(Float)
    a_0_1 = Column(Float)
    a_0_2 = Column(Float)
    a_0_3 = Column(Float)
    a_1_0 = Column(Float)
    a_1_1 = Column(Float)
    a_1_2 = Column(Float)
    a_2_0 = Column(Float)
    a_2_1 = Column(Float)
    a_3_0 = Column(Float)
    b_order = Column(Integer)
    b_0_0 = Column(Float)
    b_0_1 = Column(Float)
    b_0_2 = Column(Float)
    b_0_3 = Column(Float)
    b_1_0 = Column(Float)
    b_1_1 = Column(Float)
    b_1_2 = Column(Float)
    b_2_0 = Column(Float)
    b_2_1 = Column(Float)
    b_3_0 = Column(Float)
    ap_order = Column(Integer)
    ap_0_0 = Column(Float)
    ap_0_1 = Column(Float)
    ap_0_2 = Column(Float)
    ap_0_3 = Column(Float)
    ap_1_0 = Column(Float)
    ap_1_1 = Column(Float)
    ap_1_2 = Column(Float)
    ap_2_0 = Column(Float)
    ap_2_1 = Column(Float)
    ap_3_0 = Column(Float)
    bp_order = Column(Integer)
    bp_0_0 = Column(Float)
    bp_0_1 = Column(Float)
    bp_0_2 = Column(Float)
    bp_0_3 = Column(Float)
    bp_1_0 = Column(Float)
    bp_1_1 = Column(Float)
    bp_1_2 = Column(Float)
    bp_2_0 = Column(Float)
    bp_2_1 = Column(Float)
    bp_3_0 = Column(Float)
    wcsaxesa = Column(Integer)
    crpix1a = Column(Float)
    crpix2a = Column(Float)
    cdelt1a = Column(Float)
    cdelt2a = Column(Float)
    cunit1a = Column(String(16))
    cunit2a = Column(String(16))
    ctype1a = Column(String(32))
    ctype2a = Column(String(32))
    crval1a = Column(Float)
    crval2a = Column(Float)
    latpolea = Column(Float)
    wcsnamea = Column(String(64))
    timesys = Column(String(16))
    mjdref = Column(Float)
    date_obs = Column(String(32))
    mjd_obs = Column(Float)
    date_beg = Column(String(32))
    mjd_beg = Column(Float)
    date_avg = Column(String(32))
    mjd_avg = Column(Float)
    date_end = Column(String(32))
    mjd_end = Column(Float)
    xposure = Column(Float)
    telapse = Column(Float)
    wcsaxesw = Column(Integer)
    wcsnamew = Column(String(64))
    cname1w = Column(String(32))
    cname2w = Column(String(32))
    crpix1w = Column(Float)
    crpix2w = Column(Float)
    cdelt1w = Column(Float)
    cdelt2w = Column(Float)
    cunit1w = Column(String(16))
    cunit2w = Column(String(16))
    ctype1w = Column(String(32))
    ctype2w = Column(String(32))
    crval1w = Column(Float)
    crval2w = Column(Float)
    pv1_3w = Column(Float)
    pv2_3w = Column(Float)
    ps1_0w = Column(String(32))
    ps2_0w = Column(String(32))
    ps1_1w = Column(String(32))
    ps2_1w = Column(String(32))
    ps1_2w = Column(String(32))
    ps2_2w = Column(String(32))
    comment = Column(String(255))
    history = Column(String(255))

    # --- Geometry + bookkeeping fields ---
    footprint = Column(Geometry("POLYGON", srid=4326), nullable=False)
    savepath = Column(VARCHAR(255), unique=True, nullable=False)
    qr_version = Column(Integer, nullable=False)

    # --- Reference names ---
    ra_column_name = "crval1"
    dec_column_name = "crval2"
    geom_column_name = "footprint"
