from sqlalchemy import Column, Integer, Float, String, Boolean, Sequence, VARCHAR
from geoalchemy2 import Geometry
from spherex.tables.base import SPHEREXBase


LATEST_QR_VERSION = 2
class ImagesTable(SPHEREXBase):
    """
    Full image table preserving the exact order of WCS header keywords.
    """

    __tablename__ = "images_full"
    __table_args__ = {"extend_existing": True}

    # --- Primary key ---
    uimageid = Column(
        Integer,
        Sequence(start=1, name="images_full_uimageid_seq"),
        autoincrement=True,
        primary_key=True,
    )

    # --- Header fields in exact order ---
    NAXIS = Column(Integer)
    NAXIS1 = Column(Integer)
    NAXIS2 = Column(Integer)
    PCOUNT = Column(Integer)
    GCOUNT = Column(Integer)

    DETECTOR = Column(Integer)
    OBSID = Column(String(64))
    EXPIDN = Column(String(64))
    DATE = Column(String(32))
    TSAMP = Column(Float)
    KOVR_A = Column(Integer)
    KOVR_R = Column(Integer)
    KOVR_P = Column(Integer)
    OVRDLY = Column(Integer)
    SURLIM = Column(Integer)
    SURDLY = Column(Integer)
    TRANDLY = Column(Integer)
    TCUT = Column(Integer)
    KEN_A = Column(Integer)
    KEN_R = Column(Integer)
    KEN_P = Column(Integer)
    KSN_A = Column(Integer)
    KSN_R = Column(Integer)
    KSN_P = Column(Integer)
    NSKIP = Column(Integer)
    NVISITROW = Column(Integer)
    NVISITCOL = Column(Integer)
    MPHAN = Column(Integer)
    NCHANNEL = Column(Integer)
    WCHANNEL = Column(Integer)
    JREF = Column(Integer)
    KREF = Column(Integer)
    JACTIVE = Column(Integer)
    KACTIVE = Column(Integer)
    SPS_TARGET = Column(Integer)
    SPS_FLAGS = Column(String(64))
    OBS_IN_SBAND = Column(String(8))
    NON_SURVEY = Column(String(8))
    SGT_LAT_MIDPT = Column(Float)
    SGT_LON_MIDPT = Column(Float)
    SGT_MIN_GCD2SAA = Column(Float)
    SPS_ELON = Column(Float)
    SPS_ELAT = Column(Float)
    SPS_EPA = Column(Float)
    L1DQAFLG = Column(String(16))
    RADESYS = Column(String(16))
    L2_N_NONLINEAR = Column(Integer)
    PSTHRESH = Column(Float)
    L2_N_PERSIST = Column(Integer)
    DETCOORD = Column(String(16))
    L2_N_HOT = Column(Integer)
    L2_N_COLD = Column(Integer)
    OMEGA_MEDIAN = Column(Float)
    OMEGA_STDDEV = Column(Float)
    FINAST = Column(Integer)
    WCSAXES = Column(Integer)
    CRPIX1 = Column(Float)
    CRPIX2 = Column(Float)
    PC1_1 = Column(Float)
    PC1_2 = Column(Float)
    PC2_1 = Column(Float)
    PC2_2 = Column(Float)
    CDELT1 = Column(Float)
    CDELT2 = Column(Float)
    CUNIT1 = Column(String(16))
    CUNIT2 = Column(String(16))
    CTYPE1 = Column(String(32))
    CTYPE2 = Column(String(32))
    CRVAL1 = Column(Float)
    CRVAL2 = Column(Float)
    LONPOLE = Column(Float)
    LATPOLE = Column(Float)
    PXSRCMSK = Column(Float)
    L2_N_SOURCE = Column(Integer)
    L2_N_OUTLIER = Column(Integer)
    PSF_FWHM = Column(Float)
    L2DQAFLG = Column(String(16))
    L2_N_TRANSIENT = Column(Integer)
    L2_N_OVERFLOW = Column(Integer)
    L2_N_SUR_ERROR = Column(Integer)
    L2_N_NONFUNC = Column(Integer)
    L2_N_DICHROIC = Column(Integer)
    L2_N_MISSING = Column(Integer)
    L2_N_FULLSAMPLE = Column(Integer)
    L2_N_PHANMISS = Column(Integer)
    A_ORDER = Column(Integer)
    A_0_0 = Column(Float)
    A_0_1 = Column(Float)
    A_0_2 = Column(Float)
    A_0_3 = Column(Float)
    A_1_0 = Column(Float)
    A_1_1 = Column(Float)
    A_1_2 = Column(Float)
    A_2_0 = Column(Float)
    A_2_1 = Column(Float)
    A_3_0 = Column(Float)
    B_ORDER = Column(Integer)
    B_0_0 = Column(Float)
    B_0_1 = Column(Float)
    B_0_2 = Column(Float)
    B_0_3 = Column(Float)
    B_1_0 = Column(Float)
    B_1_1 = Column(Float)
    B_1_2 = Column(Float)
    B_2_0 = Column(Float)
    B_2_1 = Column(Float)
    B_3_0 = Column(Float)
    AP_ORDER = Column(Integer)
    AP_0_0 = Column(Float)
    AP_0_1 = Column(Float)
    AP_0_2 = Column(Float)
    AP_0_3 = Column(Float)
    AP_1_0 = Column(Float)
    AP_1_1 = Column(Float)
    AP_1_2 = Column(Float)
    AP_2_0 = Column(Float)
    AP_2_1 = Column(Float)
    AP_3_0 = Column(Float)
    BP_ORDER = Column(Integer)
    BP_0_0 = Column(Float)
    BP_0_1 = Column(Float)
    BP_0_2 = Column(Float)
    BP_0_3 = Column(Float)
    BP_1_0 = Column(Float)
    BP_1_1 = Column(Float)
    BP_1_2 = Column(Float)
    BP_2_0 = Column(Float)
    BP_2_1 = Column(Float)
    BP_3_0 = Column(Float)
    WCSAXESA = Column(Integer)
    CRPIX1A = Column(Float)
    CRPIX2A = Column(Float)
    CDELT1A = Column(Float)
    CDELT2A = Column(Float)
    CUNIT1A = Column(String(16))
    CUNIT2A = Column(String(16))
    CTYPE1A = Column(String(32))
    CTYPE2A = Column(String(32))
    CRVAL1A = Column(Float)
    CRVAL2A = Column(Float)
    LATPOLEA = Column(Float)
    WCSNAMEA = Column(String(64))
    TIMESYS = Column(String(16))
    MJDREF = Column(Float)
    DATE_OBS = Column(String(32))
    MJD_OBS = Column(Float)
    DATE_BEG = Column(String(32))
    MJD_BEG = Column(Float)
    DATE_AVG = Column(String(32))
    MJD_AVG = Column(Float)
    DATE_END = Column(String(32))
    MJD_END = Column(Float)
    XPOSURE = Column(Float)
    TELAPSE = Column(Float)
    WCSAXESW = Column(Integer)
    WCSNAMEW = Column(String(64))
    CNAME1W = Column(String(32))
    CNAME2W = Column(String(32))
    CRPIX1W = Column(Float)
    CRPIX2W = Column(Float)
    CDELT1W = Column(Float)
    CDELT2W = Column(Float)
    CUNIT1W = Column(String(16))
    CUNIT2W = Column(String(16))
    CTYPE1W = Column(String(32))
    CTYPE2W = Column(String(32))
    CRVAL1W = Column(Float)
    CRVAL2W = Column(Float)
    PV1_3W = Column(Float)
    PV2_3W = Column(Float)
    PS1_0W = Column(String(32))
    PS2_0W = Column(String(32))
    PS1_1W = Column(String(32))
    PS2_1W = Column(String(32))
    PS1_2W = Column(String(32))
    PS2_2W = Column(String(32))
    COMMENT = Column(String(255))
    HISTORY = Column(String(255))

    # --- Geometry + bookkeeping fields ---
    footprint = Column(Geometry("POLYGON", srid=4326), nullable=False)
    savepath = Column(VARCHAR(255), unique=True, nullable=False)
    qr_version = Column(Integer, nullable=False)

    # --- Reference names ---
    ra_column_name = "CRVAL1"
    dec_column_name = "CRVAL2"
    geom_column_name = "footprint"
